# Nama      : Aliza Muslimah #
# Program : Introduction to Python for Data Science #

In [6]:
import numpy as np

In [2]:
numpy.__version__


'1.20.3'

In [3]:
numpy.NaN

nan

In [4]:
numpy.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#array = struktur data central dari perpustakaan numpy

In [12]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #array 3 dimensi
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a[1] #bisa slicing

array([5, 6, 7, 8])

Bentuk array adalah tuple bilangan bulat nonnegatuf yang menentukan ukuran setioa dimensi

In [14]:
np.array([[0,0,0],[1,1,1]])

array([[0, 0, 0],
       [1, 1, 1]])

semua elemen dalama array numpy harus homogen (datatype sama)

In [15]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [18]:
np.arange(4)

array([0, 1, 2, 3])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(2,29,5) #barisan aritmatika

array([ 2,  7, 12, 17, 22, 27])

In [29]:
#add, remove, sort
arr = np.array([[2,1,3,4,5,6,7,8],[3,4,5,1,2,6,7,8]])
arr

array([[2, 1, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 1, 2, 6, 7, 8]])

In [22]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [24]:
x = [1,2]
x.append([10,11])
x #jadinya malah lis dalam list

[1, 2, [10, 11]]

In [25]:
np.delete(arr, 1) #menghapus elemen berindeks 1

array([1, 3, 4, 5, 6, 7, 8])

In [30]:
np.sort(arr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [31]:
#SHape and size
arr.ndim #brp dimensi arraynya

2

In [32]:
arr.size #elemennya ada 16

16

In [33]:
arr.shape #2 baris dan 8  kolom

(2, 8)

In [35]:
arr = np.array([[[0,1,2,3],
           [4,5,6,7]],
          
          [[0,1,2,3],
           [4,5,6,7]],
          [[0,1,2,3],
          [4,5,6,7]]
         ])
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [36]:
arr.ndim

3

In [37]:
arr.size

24

In [38]:
arr.shape

(3, 2, 4)

In [39]:
arr = np.array([[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5]])

In [41]:
arr.ndim

2

In [42]:
arr.size

5

In [43]:
arr.shape

(1, 5)

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a.reshape(3,2) #reshape array 1 dimensi mjd 2 dimensi, 3 row dan 2 kolom

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [54]:
a.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [58]:
a2 = a[np.newaxis]
a2.shape

(1, 6)

In [59]:
a2 #array dengan 2 dimensi

array([[1, 2, 3, 4, 5, 6]])

In [65]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [66]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [68]:
#nambah kolom
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [69]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [70]:
#perluas array dgn memasukkan axis baru
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [72]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [73]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [74]:
c = np.expand_dims(a, axis=0) #menambhakan dimesni ke array
c.shape

(1, 6)

In [75]:
c

array([[1, 2, 3, 4, 5, 6]])

# Indexing and Slicing

In [78]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [80]:
data[0]

1

In [81]:
data[2]

3

In [83]:
data[0:2] #array dgn indeks 0 dan 1

array([1, 2])

In [84]:
data[1:]

array([2, 3])

In [85]:
data[-2:]

array([2, 3])

In [87]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [90]:
a[condition]

In [91]:
condition = (a>=5)
a[condition]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [92]:
condition = (a%2==0) #a yang bisa dibagi dengan 2
a[condition]

array([ 2,  4,  6,  8, 10, 12])

In [93]:
condition = (a>=2) & (a<=11)
a[condition]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
a[(a>=2) & (a<=11)]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Creating array from existing data

In [96]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr1 = arr[3:8] #dari array yg kita punya bisa dislice mjd array baru
arr1

array([4, 5, 6, 7, 8])

In [99]:
a_1= np.array([[1,1],[2,2]])
a_2= np.array([[3,3],[4,4]])

In [100]:
a_1

array([[1, 1],
       [2, 2]])

In [101]:
a_2

array([[3, 3],
       [4, 4]])

In [103]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [104]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [105]:
np.hstack((a_1,a_2)).shape

(2, 4)

In [108]:
arrsplit= np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
        [13,14,15,16,17,18,19,20,21,22,23,24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [109]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [110]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [194]:
a.shape

(4,)

# Basic Array Operations
penambahan, pengurangan, dll

In [ ]:
array_1 - array_2
array_1 + array_2
array_1 * array_2
array_1 / array_2

In [113]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [114]:
a.sum()

10

In [117]:
b = np.array([[1,1],[2,3]])
b

array([[1, 1],
       [2, 3]])

In [118]:
b.sum(axis=0)

array([3, 4])

In [119]:
b.sum(axis=1)

array([2, 5])

In [130]:
data = np.array([1,2])
data

array([1, 2])

In [123]:
ones = np.ones(2)
ones

array([1., 1.])

In [124]:
data + ones

array([2., 3.])

In [125]:
data * ones

array([1., 2.])

In [126]:
data / ones

array([1., 2.])

In [127]:
data - ones

array([0., 1.])

# Broadcasting
operasi antar array

In [128]:
data

array([1, 2])

In [131]:
data * 1.6

array([1.6, 3.2])

# More array opertaion

In [132]:
data.max()

2

In [133]:
data.min()

1

In [135]:
data.sum()

3

# Matrices

In [ ]:
#list of list

In [137]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [138]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [139]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [141]:
np.random.random((3,2))

array([[0.45054308, 0.18779929],
       [0.09947973, 0.24249535],
       [0.26254209, 0.83012859]])

In [144]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [147]:
ones = np.ones([2,2])
ones

array([[1., 1.],
       [1., 1.]])

In [148]:
data * ones


array([[1., 2.],
       [3., 4.]])

In [149]:
data - ones

array([[0., 1.],
       [2., 3.]])

In [150]:
data / ones

array([[1., 2.],
       [3., 4.]])

# Dot Product

In [152]:
a_1 = np.array([[1,2,3],[4,5,6]])
a_1.shape

(2, 3)

In [153]:
a_2 = np.array([[7,8],[9,10],[11,12]])
a_2.shape

(3, 2)

In [154]:
np.dot(a_1,a_2)  #rumus dot product

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [155]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [157]:
data[0][1]

2

In [159]:
data[0,1]

2

In [160]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [163]:
data[0:2,1]

array([2, 4])

# Matrix aggregation

In [164]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [165]:
data.max()

6

In [166]:
data.sum()

21

In [167]:
data.std()

1.707825127659933

In [168]:
data.max(axis=0)

array([5, 6])

In [169]:
data.max(axis=1)

array([2, 4, 6])

# Transposing and reshaping

In [170]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [172]:
data.T #rumus transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [173]:
data_col = np.array([[1,2,3,4,5,6]])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [175]:
data_col = data_col.T
data_col

array([[1, 2, 3, 4, 5, 6]])

In [176]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [178]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [179]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# N-dimensional array

In [181]:
ndarr = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]
                 ])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [182]:
ndarr.shape

(2, 2, 2)

In [183]:
np.ones([4,3,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [184]:
np.zeros([4,3,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [187]:
np.random.random((4,3,2))

array([[[0.4895159 , 0.05090727],
        [0.85725039, 0.30723621],
        [0.09683308, 0.34626099]],

       [[0.0734283 , 0.76358372],
        [0.96463306, 0.73448416],
        [0.10894336, 0.54652073]],

       [[0.64810168, 0.19096263],
        [0.71621312, 0.74810856],
        [0.44728494, 0.55493228]],

       [[0.17720393, 0.18013953],
        [0.75547377, 0.99712194],
        [0.76839787, 0.33601209]]])

# Flatten N-dimensional array

In [188]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [189]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [190]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [193]:
error = (1/n) * np.sum(np.square(observed - prediction))